# @package _global_
defaults:
  - _self_
  - env: ant
  - agent: sb3_ppo
  - learner: sb3_learner
  - callbacks: default
  - hparams_search: null
  - experiment: null

seed: 1234

task_name: "train_save_best"
log_dir: ./logs

run_id: ${task_name}/${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${log_dir}/runs/${run_id}
  sweep:
    dir: ${log_dir}/multiruns/${run_id}
    subdir: ${hydra.job.num}

#checkpoint_path: ${hydra:runtime.output_dir}/checkpoints
tensorboard_path: ${hydra:runtime.output_dir}/tensorboard

trained_agents_dir: ${hydra:runtime.cwd}/trained_agents

# default: single-run => no suffix; for sweeps, override this from CLI
# e.g. python -m train ... job_num_suffix="/${hydra.job.num}"
job_num_suffix: ""
trained_agents_path: ${trained_agents_dir}/${run_id}${job_num_suffix}

# use these everywhere you save models
checkpoint_path: ${trained_agents_path}/checkpoints
best_model_path: ${trained_agents_path}/best_model
final_model_path: ${trained_agents_path}/final